version: '3.5'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: somerandompassword
      POSTGRES_DB: freighty
      PGDATA: /data/postgres
    volumes:
       - pgdata:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata: